export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';

export const WORKSPACE_REQUEST = 'WORKSPACE_REQUEST';
export const WORKSPACE_SUCCESS = 'WORKSPACE_SUCCESS';
export const WORKSPACE_FAILED = 'WORKSPACE_FAILED';
