export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';

export const WORKSPACE_CREATE_REQUEST = 'WORKSPACE_CREATE_REQUEST';
export const WORKSPACE_CREATE_SUCCESS = 'WORKSPACE_CREATE_SUCCESS';
export const WORKSPACE_CREATE_FAILED = 'WORKSPACE_CREATE_FAILED';

export const WORKSPACE_GET_REQUEST = 'WORKSPACE_GET_REQUEST';
export const WORKSPACE_GET_SUCCESS = 'WORKSPACE_GET_SUCCESS';
export const WORKSPACE_GET_FAILED = 'WORKSPACE_GET_FAILED';

// Get selected workspace constants
export const GET_CURRENT_WORKSPACE_REQUEST = 'GET_CURRENT_WORKSPACE_REQUEST';
export const GET_CURRENT_WORKSPACE_SUCCESS = 'GET_CURRENT_WORKSPACE_SUCCESS';
export const GET_CURRENT_WORKSPACE_FAILED = 'GET_CURRENT_WORKSPACE_FAILED';

export const POST_TEAM_MEMBER_REQUEST = 'POST_TEAM_MEMBER_REQUEST';
export const POST_TEAM_MEMBER_SUCCESS = 'POST_TEAM_MEMBER_SUCCESS';
export const POST_TEAM_MEMBER_FAILED = 'POST_TEAM_MEMBER_FAILED';

export const GET_MEMBERS_REQUEST = 'GET_MEMBERS_REQUEST';
export const GET_MEMBERS_SUCCESS = 'GET_MEMBERS_SUCCESS';
export const GET_MEMBERS_FAILED = 'GET_MEMBERS_FAILED';

// add & post tasks
export const POST_TASK_REQUEST = 'POST_TASK_REQUEST';
export const POST_TASK_SUCCESS = 'POST_TASK_SUCCESS';
export const POST_TASK_FAILED = 'POST_TASK_FAILED';

export const GET_TASK_REQUEST = 'GET_TASK_REQUEST';
export const GET_TASK_SUCCESS = 'GET_TASK_SUCCESS';
export const GET_TASK_FAILED = 'GET_TASK_FAILED';

export const EDIT_TASK_REQUEST = 'EDIT_TASK_REQUEST';
export const EDIT_TASK_SUCCESS = 'EDIT_TASK_SUCCESS';
export const EDIT_TASK_FAILED = 'EDIT_TASK_FAILED';
