export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';

export const WORKSPACE_CREATE_REQUEST = 'WORKSPACE_CREATE_REQUEST';
export const WORKSPACE_CREATE_SUCCESS = 'WORKSPACE_CREATE_SUCCESS';
export const WORKSPACE_CREATE_FAILED = 'WORKSPACE_CREATE_FAILED';

export const WORKSPACE_GET_REQUEST = 'WORKSPACE_GET_REQUEST';
export const WORKSPACE_GET_SUCCESS = 'WORKSPACE_GET_SUCCESS';
export const WORKSPACE_GET_FAILED = 'WORKSPACE_GET_FAILED';
